# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  pull-requests: write
  contents: read

jobs:
  validate_pr_title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        id: lint_pr_title
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          ignoreLabels: |
            ignore-semantic-pr
          subjectPattern: "^(?![A-Z]).+$"
          types: |
            build
            chore
            ci
            deps
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
            release
          scopes: |
            gui
            config
            dirclient
            oasf
            docker
            .*
          requireScope: false

      - uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Hey there and thank you for opening this pull request! 👋

            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/),
            and it looks like your proposed title needs to be adjusted.

            Details:

            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```

      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        with:
          header: pr-title-lint-error
          delete: true

  label:
    name: Label
    runs-on: ubuntu-latest
    steps:
      - uses: codelytv/pr-size-labeler@095a41fca88b8764fd9e008ad269bcdb82bb38b9 # v1.10.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: "size/XS"
          xs_max_size: "50"
          s_label: "size/S"
          s_max_size: "200"
          m_label: "size/M"
          m_max_size: "1000"
          l_label: "size/L"
          l_max_size: "2000"
          xl_label: "size/XL"
          fail_if_xl: "false"
          message_if_xl: >
            This PR exceeds the recommended size of 2000 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
          files_to_ignore: |
            "*.md"
            "**/go.sum"
            "**/go.mod"
